### ISSUE TITLE
[BYPASS] Watchdog Full Disabler bans

### ISSUE THREAD

**Issue by Clumsy0420** [MonsoonDevelopment/Monsoon-Issues#4]
**Server/Anticheat**
The server and/or Anticheat that the bypass no longer works on.

**Module or modules**
The modules that are affected by this.

**To Reproduce**
(E.G.)

1. Go on the server '....'
2. Enable the module '....' with the settings '....'
3. Flag!!! What is go on???

**Expected behavior**

**Screenshots and/or video**

**Additional context**

**Comment by laika-cosmonaut** [comment]
Formatted incorrectly, issue submission rejected
