### ISSUE TITLE
[BUG] my game liteally does load in intent

### ISSUE THREAD

**Issue by Mairion** [MonsoonDevelopment/Monsoon-Issues#6]
**Describe the bug**

**To Reproduce**
press load on intent

**Expected behavior**
The game to open
**Screenshots**

**Desktop (computer):**

- OS: windoes

**Additional context**

**Comment by laika-cosmonaut** [comment]
Monsoon cannot be used on Intent. This was detailed when purchasing and has been publicly known for quite some time.

**Comment by Kobley** [comment]
stupid dummy

**Comment by laika-cosmonaut** [comment]
> stupid dummy

kobley ily
